version: '3'
services:
  database:
    image: "postgres" 
    ports:
      - 5432:5432
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=password
      -  POSTGRES_DB=discordbot
    volumes:
      - ./dbdemo/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer:latest
    ports:
      - 7000:8080