version: '3'
services:
  database:
    image: "postgres" 
    ports:
      - 5432:5432
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=password
      -  POSTGRES_DB=discordbot
    volumes:
      - database-data:/var/lib/postgresql/data/ 

  adminer:
    image: adminer:latest
    ports:
      - 7000:8080

volumes:
  database-data: 